# Generated by Django 5.0.7 on 2024-08-06 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='categry',
        ),
    ]
